[package]
name = "deep_vision"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "deep_vision"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.3"
